theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core June/July 2019 scRNA-Seq Workshop @ UCD and UCSF'
tagline: 'June 24-27/July 1-3, 2019'
name: 'UC Davis Bioinformatics Core June/July 2019 scRNA-Seq Workshop @ UCD and UCSF'
github:
  repository_url: https://github.com/ucdavis-bioinformatics-training/2019-single-cell-RNA-sequencing-Workshop-UCD_UCSF
